// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfHoDL0R7mvHUpMpTgjDouefGNmbQs_GA',
    appId: '1:719185517824:web:8982097ada8ce21e9567e5',
    messagingSenderId: '719185517824',
    projectId: 'ecommerceapp-f267f',
    authDomain: 'ecommerceapp-f267f.firebaseapp.com',
    storageBucket: 'ecommerceapp-f267f.firebasestorage.app',
    measurementId: 'G-WR894LVCXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6uTdLPyydA9BOqHLiO3i5E_3cR8M-Mnc',
    appId: '1:719185517824:android:7863bf17c96cfb2a9567e5',
    messagingSenderId: '719185517824',
    projectId: 'ecommerceapp-f267f',
    storageBucket: 'ecommerceapp-f267f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTs7jkz8FT-l4r8LR0HjNtCRiDThM9zIs',
    appId: '1:719185517824:ios:61e5a760a3e306379567e5',
    messagingSenderId: '719185517824',
    projectId: 'ecommerceapp-f267f',
    storageBucket: 'ecommerceapp-f267f.firebasestorage.app',
    iosClientId: '719185517824-5faicvadbpus96benhe6v78gqrnm6erl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTs7jkz8FT-l4r8LR0HjNtCRiDThM9zIs',
    appId: '1:719185517824:ios:61e5a760a3e306379567e5',
    messagingSenderId: '719185517824',
    projectId: 'ecommerceapp-f267f',
    storageBucket: 'ecommerceapp-f267f.firebasestorage.app',
    iosClientId: '719185517824-5faicvadbpus96benhe6v78gqrnm6erl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfHoDL0R7mvHUpMpTgjDouefGNmbQs_GA',
    appId: '1:719185517824:web:3a5a0a5293d7381c9567e5',
    messagingSenderId: '719185517824',
    projectId: 'ecommerceapp-f267f',
    authDomain: 'ecommerceapp-f267f.firebaseapp.com',
    storageBucket: 'ecommerceapp-f267f.firebasestorage.app',
    measurementId: 'G-KPWSTF7WXD',
  );

}